# Generated by Django 5.2.1 on 2025-06-04 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DanhMuc",
            fields=[
                (
                    "danh_muc",
                    models.CharField(max_length=150, primary_key=True, serialize=False),
                ),
                ("loai", models.CharField(max_length=150)),
                ("so_luong", models.IntegerField()),
                ("tao_luc", models.DateTimeField(auto_now_add=True)),
                ("cap_nhat_luc", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="NhaCungCap",
            fields=[
                (
                    "nha_cung_cap",
                    models.CharField(max_length=150, primary_key=True, serialize=False),
                ),
                ("ten_lien_he", models.CharField(max_length=150)),
                ("duong_dan", models.CharField(max_length=150)),
                ("tai_san", models.IntegerField()),
                ("tao_luc", models.DateTimeField(auto_now_add=True)),
                ("cap_nhat_luc", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="NhanVien",
            fields=[
                (
                    "ma_nhan_vien",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("ten", models.CharField(max_length=150)),
                ("ho", models.CharField(max_length=150)),
                ("ten_dang_nhap", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="NhaSanXuat",
            fields=[
                (
                    "nha_san_xuat",
                    models.CharField(max_length=150, primary_key=True, serialize=False),
                ),
                ("tai_san", models.IntegerField()),
                ("tao_luc", models.DateTimeField(auto_now_add=True)),
                ("cap_nhat_luc", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ViTri",
            fields=[
                (
                    "vi_tri",
                    models.CharField(max_length=150, primary_key=True, serialize=False),
                ),
                ("so_nguoi", models.IntegerField()),
                ("dia_chi", models.CharField(max_length=150)),
                ("thanh_pho", models.CharField(max_length=150)),
                ("tao_luc", models.DateTimeField(auto_now_add=True)),
                ("cap_nhat_luc", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TaiSan",
            fields=[
                (
                    "ma_tai_san",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("ten_tai_san", models.CharField(max_length=150)),
                ("so_serial", models.CharField(max_length=150)),
                ("gia_mua", models.DecimalField(decimal_places=2, max_digits=150)),
                (
                    "danh_muc",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="qlts.danhmuc",
                    ),
                ),
                (
                    "ma_nhan_vien",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="qlts.nhanvien",
                    ),
                ),
                (
                    "nha_cung_cap",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="qlts.nhacungcap",
                    ),
                ),
                (
                    "nha_san_xuat",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="qlts.nhasanxuat",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="nhanvien",
            name="vi_tri",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="qlts.vitri"
            ),
        ),
    ]
